### ISSUE TITLE
Improve Voice Generation to Match Original Bass Tone

### ISSUE THREAD

**Issue by vtennero** [aedocw/epub2tts#262]
I'm using a French voice to run epubtts on an ebook. The problem I'm encountering is that the original voice sample (which is similar to Jean Reno's voice) has significantly more bass compared to the generated voice from the epub.

I've attached audio samples for both the original and generated voices for comparison:
Original voice
https://www.dropbox.com/scl/fi/rwlk58zt2t8vzawea83p1/renomerged.mp3?rlkey=mejqm8n2yedl9ko9tfu4r5efa&st=ikkomh39&dl=0

Generated voice
https://www.dropbox.com/scl/fi/d5ydu4z6l1dhr3wmu3wv7/desert01-renomerged.m4b?rlkey=qp10siskjt3gat9pvb2d6jxlk&st=503rio4t&dl=0

Could you provide any tips or guidance on how to adjust the generated voice to more closely match the bass tone of the original voice? Are there settings in epubtts or external tools that could help achieve this?

**Comment by aedocw** [comment]
This is something that would have to be fixed with XTTS, and fine tuning. Sorry, I don't have a lot of experience there but if you check out the coqui docs there's a link to their discord. I haven't been there in a while but last I remember (a few months ago), there were lots of folks there and they were pretty helpful.
